# Generated by Django 4.0.2 on 2022-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_TAG',
            field=models.CharField(default='My BLOG! ', max_length=255),
        ),
    ]
