# Generated by Django 4.0.1 on 2022-02-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0006_alter_produkty_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='producent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.producent'),
        ),
    ]
