# Generated by Django 4.0.1 on 2022-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0007_alter_produkty_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='obrazek',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
